level4_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# Template tagging
app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other_page')
]

level4_templates/level4_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
]

level4_templates/basic_app/models.py
from django.db import models

# Create your models here.

level4_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

level4_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- link to bootstrap  -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other_page'%}">Other</a>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block%}
      <!-- Anything outside of this will be inherited if u extend -->
      {% endblock %}

    </div>
  </body>
</html>
<!--  -->

level4_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
 {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is index.html with template inheritance</h2>
    <h1>{{ text|upper}}</h1>
    <h2>{{ number|add:"99" }}</h2>
    <h1>{{ text|cut:'world'}}</h1>
  {% endblock %}

level4_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is an example of template inheritance! </h2>
  {% endblock %}

level4_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basic_app:other_page' %}">The other page</a>
    <!-- Go to admin page using ancher tags -->
    </br><a href="{% url 'admin:index' %}">admin-index</a>
    <!-- Go to index page -->
    <a href="{% url 'index' %}">Link to index</a>
  </body>
</html>